#!/bin/sh
s="󰐥 Shutdown\n󰜉 Restart\n󰍃 Logout\n󰌾 Lock\n󰍺 Auto-configure monitors"
case $RMENU in
    rofi) cmd=$(echo -e "$s" | 
    rofi -dmenu -i -no-show-icons -p "󰐦 Power");;
    dmenu) cmd=$(echo -e "$s" | 
    dmenu -i -fn 'Jetbrains Mono:bold:pixelsize=16' -nb $BG -nf $LIGHTGREY -sb $LIGHTGREY -sf $BG -p "󰐦 Power");;
esac

echo $cmd
case $cmd in
        󰐥\ Shutdown) exec systemctl poweroff;;
        󰜉\ Restart) exec systemctl reboot;;
        # Logout) kill -HUP $XDG_SESSION_PID;;
        󰍃\ Logout) i3-msg exit;;
        󰌾\ Lock) exec systemctl suspend;;
        󰍺\ Auto-configure\ monitors) exec fix-monitors;;
        #Lock) exec systemctl --user start lock.target;;
esac